---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: LoadBalancer
  ports:
    - name: http-server
      port: 80
      targetPort: 3000
  selector:
    app: <APP_NAME>
    tier: frontend